import SwiftUI

extension Color {
	static let transparent = white.opacity(0)
	static let lightBlue = Self("LightBlue")
	static let mediumBlue = Self("MediumBlue")
	static let darkBlue = Self("DarkBlue")
	static let lightGrayBackground = Self("LightGrayBackground")
	static let lightGray = Self("LightGray")
	static let mediumGray = Self("MediumGray")
	static let darkGray = Self("DarkGray")
	static let neonGreen = Self("NeonGreen")
	static let lightGreen = Self("LightGreen")
	static let bluePurple = Self("BluePurple")
	static let grayShadow = black.opacity(0.0787)
	static let transparentLightGray = lightGray.opacity(0.1624)
	static let darkText = Self("DarkText")
	static let disabledButtonBackground = Self("DisabledButtonBackground")
	static let darkRed = Self("DarkRed")
	static let extraBluePurple = Self("ExtraBluePurple")
	static let darkerLightBlue = Self("DarkerLightBlue")
	static let lightGrayText = Self("LightGrayText")
	static let lightGrayBorder = Self("LightGrayBorder")
	static let extraPurple = Self("ExtraPurple")
	static let lightGrayLine = Self("LightGrayLine")
	static let unselectedTabBarItem = Self("UnselectedTabBarItem")
	static let neonOrange = Self("NeonOrange")
	static let neonRed = Self("NeonRed")
}
